[tasks]
  [tasks.dev]
  depends = "dev:*"

  [tasks."dev:container"]
  run = [
    "podman compose down",
    "podman compose build --progress=plain",
    "podman compose up"
  ]

  [tasks."dev:screen"]
  run = "Xephyr -screen 1024x768 :7"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
